[tool.poetry]
name = "ice-cream-dataops"
version = "0.1.0"
description = ""
authors = ["August van der Sluijs"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
cognite-toolkit = "0.6.53"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
